name: fuk_ui_kit
description: A Flutter UI Kit for desktop and web applications.
homepage: https://github.com/cesarmod2017/fuk_ui_kit
repository: https://github.com/cesarmod2017/fuk_ui_kit
version: 0.0.11

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.1.0
  file_picker: ^8.0.5
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
